### ISSUE TITLE
Manually copying to Windows

### ISSUE THREAD

**Issue by Todann** [biscuits99/rp-video-manager#15]
Hi, this tools seems really useful and I'd like to use these bezels with Retroarch, except I'm setting this up on my Windows 10 computer, and don't want to manually configure every bezel for every game. It seems like I should be able to just copy and paste these folders like the program does anyways, but none of the folder names seem to line up. I've searched through all the Retroarch folders and tried to look at the coding of videomanager.sh, but as I said the folder names don't match up, I'm assuming it because the retropie version is quite different. Does anyone know the locations these main folders go into on the Windows version? Any help would be greatly appreciated.

**Comment by biscuits99** [comment]
You may want to check this thread if you are using windows:
https://forums.libretro.com/t/arcade-overlays/4084/

**Comment by Todann** [comment]
Awesome this is helpful, doesn't have the automatic script yet it seems but can't have everything I guess, thanks.
