### ISSUE TITLE
Installtion????

### ISSUE THREAD

**Issue by nemo1966** [biscuits99/rp-video-manager#6]
wget https://github.com/biscuits99/rp-video-manager/releases/download/{release-number}/rp-video-manager.zip

What is {release-number}? Should I use the force to guess what it is?

Release number of this utility? Release number of retropie? release number of Star Wars?

**Comment by biscuits99** [comment]
Yes, use the force in the first instance, if that fails use the release tab info:
https://github.com/biscuits99/rp-video-manager/releases
