### ISSUE TITLE
overscan when using a arcade bezel

### ISSUE THREAD

**Issue by txcx** [biscuits99/rp-video-manager#7]
hi,

first i want to thank you for this little nice project, gonna help me to get a fast nice setting of crt scanlines, but i stumpled upon an issue.

i use a lcd display through hdmi and had a black border at retropie first time setup. so i tried to disable this, i can't remember what cfg or settings file i edited but i got the display now exactly full covered.

weeks after that i tried yesterday our rp video manager, everything seems fine but i discovered if i start final fight for mame the arcade bezels (i've turned them on) covers parts of the game, 20-30% are under the bezel (each side), and i don't know why.

is there a way to reset my own overscan settings or is it a issue with the video manager maybe?

thank you for any help :)
keep up the good work.

**Comment by biscuits99** [comment]
Thanks for the comments. The arcade bezels assume a 1080p resolution will be used.
If you are running a different resolution, you can compensate for this by editing the /home/pi/RetroPie/roms/mame-libretro/romname.zip.cfg

Some info here:
http://www.jammaplus.co.uk/forum/forum_posts.asp?TID=75939&PID=719797&title=emulation-on-pi#719797

**Comment by txcx** [comment]
Thanks for the information, i could remove a initial setting (640x480) in retroarch.cfg done by myself, this helped me a bit, anyhow there is still a bit covered by the bezel (e.g. final fight world set in mame, around .75 inch on each side), maybe i have to play with the overscan settings?

**Comment by biscuits99** [comment]
For an example showing how to tweak the output, try the invinco.zip.cfg file.
I'd leave the retroarch.cfg alone.
Bear in mind the aspect ratio, i.e final fight is 384x224 (1.71:1)
https://en.wikipedia.org/wiki/Final_Fight

**Comment by txcx** [comment]
ty for your help, i'll have a look at this :)
