### ISSUE TITLE
Ratio changes itself after first start 

### ISSUE THREAD

**Issue by prenand** [biscuits99/rp-video-manager#8]
I have a problem. Installed the tool without problems. In menu activated the 1080p overlays. 
Then after activation the first rom starts without problems. Overlays and everything fine.  Just like it has to be. But after closing first rom, all starts after that the ratio changes itself to fullscreen. In all emulators. Overlays are still there but the game ratio doesnt fit there anymore. Its fullscreen. Tried already to reinstall and everything. Reboot doesnt help. Only solution is to activate the overlays again in rp Video Manager. But Just for one rom. Seems like the settings for ratio are changing after first start. 
Here the difference between first and second start. 

https://www.dropbox.com/sh/uievbgqhtra0sok/AABxL-Ocy_S30TwcVkvqhlosa?dl=0

**Comment by biscuits99** [comment]
Which version of RetroPie are you running?
Would you be able to package your config files before and after?
http://smartretro.co.uk/forums/viewtopic.php?f=3&t=8289

**Comment by prenand** [comment]
I use the newest version of retropie. Just installed last weekend, i think 3.8.1.
Ok, i will show them later after work. 
Very confusing.... First start everything works. After closing the first rom, the games i start after that are in fullscreen, not fitting to the overlay.

**Comment by prenand** [comment]
Problem solved!
I had no time to check all cfg files, so I backed up all my games and reinstalled retropie with a new sd image. 
Now rp video manager and the overlays work fine. Thanks for the nice tool, everything looks much better with the overlays and tv borders.
