### ISSUE TITLE
Syntax error: "do" unexpected

### ISSUE THREAD

**Issue by R1MnTnA** [biscuits99/rp-video-manager#9]
Followed the directions and when I run ./videomanager.sh I receive the Syntax error: "do" unexpected (expecting "done") on line 18.

**Comment by biscuits99** [comment]
Which version of RetroPie and the video manager tool are you using?

**Comment by R1MnTnA** [comment]
RetroPie is v3.8.1 and Vid-Manager is current v1.1

**Comment by R1MnTnA** [comment]
Never mind I'm sorry. I was running it under sudo. Not needed. Thanks and sorry again for the mix up. Awesome Repo and work Thank you so much!
